name: Compile Firmware

on:
  push:
    paths:
      - 'firmware/**'
  pull_request:
    paths:
      - 'firmware/**'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Cache Arduino Core and Libraries
        uses: actions/cache@v3
        with:
          path: |
            ~/.arduino15
            ~/Arduino/libraries
          key: ${{ runner.os }}-arduino-${{ hashFiles('firmware/Dilla4x_v0.2/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-arduino-

      - name: Install Dependencies
        working-directory: ./firmware/Dilla4x_v0.2
        run: make install-deps

      - name: Compile Firmware
        working-directory: ./firmware/Dilla4x_v0.2
        run: make compile

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dilla4x-Firmware-Hex
          path: firmware/Dilla4x_v0.2/build/*.hex
